version: '3'

services:
  app:
    image: 'thloykot/geometry-app'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: geometryApp
    depends_on:
      - db
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gis
      - SPRING_DATASOURCE_USERNAME=r
      - SPRING_DATASOURCE_PASSWORD=r


  db:
    image: 'kartoza/postgis'
    container_name: postgres
    environment:
      - POSTGRES_USER=r
      - POSTGRES_PASS=r
